
const types = {
  setFamilies:"set_families",
  setFavorites:"set_favorites",
  setHistory:"set_history",
  setIngredients:"set_ingredients",
  setRecipes:"set_recipes",
  signin:"signin",
  signout:"signout",
  sessionUpdate:"session_update",
  setUnits:"set_units",
  setStyles:"set_styles",
  addLeftMenu:"add_left_menu",
  removeLeftMenu:"remove_left_menu",




  ADD_NUMBER_OF_PROPOSITION:"ADD_NUMBER_OF_PROPOSITION",
  ADD_ONE_INGREDIENT_CHOICES: "ADD_ONE_INGREDIENT_CHOICES",
  ADD_ONE_FAMILY_CHOICES:"ADD_ONE_FAMILY_CHOICES",
  SUBTRACT_NUMBER_OF_PROPOSITION:"SUBTRACT_NUMBER_OF_PROPOSITION",
  SET_HUNGER_BIG:"SET_HUNGER_BIG",
  SET_HUNGER_NORMAL:"SET_HUNGER_NORMAL",
  SET_HUNGER_FEW:"SET_HUNGER_FEW",
  SET_PREPARATING_TIME:"SET_PREPARATING_TIME",
  SET_COOKING_TIME:"SET_COOKING_TIME",
  SET_FAVORITES_RECIPES:"SET_FAVORITES_RECIPES",
  SET_INGREDIENTS_CHOICES:"SET_INGREDIENTS_CHOICES",
  GENERATE_PROPOSAL:"GENERATE_PROPOSAL",
  GENERATED_PROPOSAL:"GENERATED_PROPOSAL",
  CLOSE_PROPOSAL:"CLOSE_PROPOSAL",
  SET_PROPOSAL:"SET_PROPOSAL",
  SET_RECIPES_QUERRY:"SET_RECIPES_QUERRY",
  SET_IS_ASIDE_TRUE: "SET_IS_ASIDE_TRUE",
  SET_IS_ASIDE_FALSE: "SET_IS_ASIDE_FALSE",
  SET_STARTER: "SET_STARTER",
  REMOVE_RECIPE_FROM_FAVORITES:"REMOVE_RECIPE_FROM_FAVORITES",
  SET_HISTORIC_PROPOSAL:"SET_HISTORIC_PROPOSAL",
  SET_RECIPES_PROPOSAL:"SET_RECIPES_PROPOSAL"
};

export default types;